#
from battlecode import BCAbstractRobot, SPECS
import battlecode as bc
from bots.first_bot.utils import *

# For CASTLE TALK 2 ^ 8 - 1
MESSAGE = {
    0: 'not_implemented_yet',
    1: 'not_implemented_yet',
    2: 'not_implemented_yet',
    3: 'not_implemented_yet',
    4: 'not_implemented_yet',
    5: 'not_implemented_yet',
    6: 'not_implemented_yet',
    7: 'not_implemented_yet',
    8: 'not_implemented_yet',
    9: 'not_implemented_yet',
    10: 'not_implemented_yet',
    11: 'not_implemented_yet',
    12: 'not_implemented_yet',
    13: 'not_implemented_yet',
    14: 'not_implemented_yet',
    15: 'not_implemented_yet',
    16: 'not_implemented_yet',
    17: 'not_implemented_yet',
    18: 'not_implemented_yet',
    19: 'not_implemented_yet',
    20: 'not_implemented_yet',
    21: 'not_implemented_yet',
    22: 'not_implemented_yet',
    23: 'not_implemented_yet',
    24: 'not_implemented_yet',
    25: 'not_implemented_yet',
    26: 'not_implemented_yet',
    27: 'not_implemented_yet',
    28: 'not_implemented_yet',
    29: 'not_implemented_yet',
    30: 'not_implemented_yet',
    31: 'not_implemented_yet',
    32: 'not_implemented_yet',
    33: 'not_implemented_yet',
    34: 'not_implemented_yet',
    35: 'not_implemented_yet',
    36: 'not_implemented_yet',
    37: 'not_implemented_yet',
    38: 'not_implemented_yet',
    39: 'not_implemented_yet',
    40: 'not_implemented_yet',
    41: 'not_implemented_yet',
    42: 'not_implemented_yet',
    43: 'not_implemented_yet',
    44: 'not_implemented_yet',
    45: 'not_implemented_yet',
    46: 'not_implemented_yet',
    47: 'not_implemented_yet',
    48: 'not_implemented_yet',
    49: 'not_implemented_yet',
    50: 'not_implemented_yet',
    51: 'not_implemented_yet',
    52: 'not_implemented_yet',
    53: 'not_implemented_yet',
    54: 'not_implemented_yet',
    55: 'not_implemented_yet',
    56: 'not_implemented_yet',
    57: 'not_implemented_yet',
    58: 'not_implemented_yet',
    59: 'not_implemented_yet',
    60: 'not_implemented_yet',
    61: 'not_implemented_yet',
    62: 'not_implemented_yet',
    63: 'not_implemented_yet',
    64: 'not_implemented_yet',
    65: 'not_implemented_yet',
    66: 'not_implemented_yet',
    67: 'not_implemented_yet',
    68: 'not_implemented_yet',
    69: 'not_implemented_yet',
    70: 'not_implemented_yet',
    71: 'not_implemented_yet',
    72: 'not_implemented_yet',
    73: 'not_implemented_yet',
    74: 'not_implemented_yet',
    75: 'not_implemented_yet',
    76: 'not_implemented_yet',
    77: 'not_implemented_yet',
    78: 'not_implemented_yet',
    79: 'not_implemented_yet',
    80: 'not_implemented_yet',
    81: 'not_implemented_yet',
    82: 'not_implemented_yet',
    83: 'not_implemented_yet',
    84: 'not_implemented_yet',
    85: 'not_implemented_yet',
    86: 'not_implemented_yet',
    87: 'not_implemented_yet',
    88: 'not_implemented_yet',
    89: 'not_implemented_yet',
    90: 'not_implemented_yet',
    91: 'not_implemented_yet',
    92: 'not_implemented_yet',
    93: 'not_implemented_yet',
    94: 'not_implemented_yet',
    95: 'not_implemented_yet',
    96: 'not_implemented_yet',
    97: 'not_implemented_yet',
    98: 'not_implemented_yet',
    99: 'not_implemented_yet',
    100: 'not_implemented_yet',
    101: 'not_implemented_yet',
    102: 'not_implemented_yet',
    103: 'not_implemented_yet',
    104: 'not_implemented_yet',
    105: 'not_implemented_yet',
    106: 'not_implemented_yet',
    107: 'not_implemented_yet',
    108: 'not_implemented_yet',
    109: 'not_implemented_yet',
    110: 'not_implemented_yet',
    111: 'not_implemented_yet',
    112: 'not_implemented_yet',
    113: 'not_implemented_yet',
    114: 'not_implemented_yet',
    115: 'not_implemented_yet',
    116: 'not_implemented_yet',
    117: 'not_implemented_yet',
    118: 'not_implemented_yet',
    119: 'not_implemented_yet',
    120: 'not_implemented_yet',
    121: 'not_implemented_yet',
    122: 'not_implemented_yet',
    123: 'not_implemented_yet',
    124: 'not_implemented_yet',
    125: 'not_implemented_yet',
    126: 'not_implemented_yet',
    127: 'not_implemented_yet',
    128: 'not_implemented_yet',
    129: 'not_implemented_yet',
    130: 'not_implemented_yet',
    131: 'not_implemented_yet',
    132: 'not_implemented_yet',
    133: 'not_implemented_yet',
    134: 'not_implemented_yet',
    135: 'not_implemented_yet',
    136: 'not_implemented_yet',
    137: 'not_implemented_yet',
    138: 'not_implemented_yet',
    139: 'not_implemented_yet',
    140: 'not_implemented_yet',
    141: 'not_implemented_yet',
    142: 'not_implemented_yet',
    143: 'not_implemented_yet',
    144: 'not_implemented_yet',
    145: 'not_implemented_yet',
    146: 'not_implemented_yet',
    147: 'not_implemented_yet',
    148: 'not_implemented_yet',
    149: 'not_implemented_yet',
    150: 'not_implemented_yet',
    151: 'not_implemented_yet',
    152: 'not_implemented_yet',
    153: 'not_implemented_yet',
    154: 'not_implemented_yet',
    155: 'not_implemented_yet',
    156: 'not_implemented_yet',
    157: 'not_implemented_yet',
    158: 'not_implemented_yet',
    159: 'not_implemented_yet',
    160: 'not_implemented_yet',
    161: 'not_implemented_yet',
    162: 'not_implemented_yet',
    163: 'not_implemented_yet',
    164: 'not_implemented_yet',
    165: 'not_implemented_yet',
    166: 'not_implemented_yet',
    167: 'not_implemented_yet',
    168: 'not_implemented_yet',
    169: 'not_implemented_yet',
    170: 'not_implemented_yet',
    171: 'not_implemented_yet',
    172: 'not_implemented_yet',
    173: 'not_implemented_yet',
    174: 'not_implemented_yet',
    175: 'not_implemented_yet',
    176: 'not_implemented_yet',
    177: 'not_implemented_yet',
    178: 'not_implemented_yet',
    179: 'not_implemented_yet',
    180: 'not_implemented_yet',
    181: 'not_implemented_yet',
    182: 'not_implemented_yet',
    183: 'not_implemented_yet',
    184: 'not_implemented_yet',
    185: 'not_implemented_yet',
    186: 'not_implemented_yet',
    187: 'not_implemented_yet',
    188: 'not_implemented_yet',
    189: 'not_implemented_yet',
    190: 'not_implemented_yet',
    191: 'not_implemented_yet',
    192: 'not_implemented_yet',
    193: 'not_implemented_yet',
    194: 'not_implemented_yet',
    195: 'not_implemented_yet',
    196: 'not_implemented_yet',
    197: 'not_implemented_yet',
    198: 'not_implemented_yet',
    199: 'not_implemented_yet',
    200: 'not_implemented_yet',
    201: 'not_implemented_yet',
    202: 'not_implemented_yet',
    203: 'not_implemented_yet',
    204: 'not_implemented_yet',
    205: 'not_implemented_yet',
    206: 'not_implemented_yet',
    207: 'not_implemented_yet',
    208: 'not_implemented_yet',
    209: 'not_implemented_yet',
    210: 'not_implemented_yet',
    211: 'not_implemented_yet',
    212: 'not_implemented_yet',
    213: 'not_implemented_yet',
    214: 'not_implemented_yet',
    215: 'not_implemented_yet',
    216: 'not_implemented_yet',
    217: 'not_implemented_yet',
    218: 'not_implemented_yet',
    219: 'not_implemented_yet',
    220: 'not_implemented_yet',
    221: 'not_implemented_yet',
    222: 'not_implemented_yet',
    223: 'not_implemented_yet',
    224: 'not_implemented_yet',
    225: 'not_implemented_yet',
    226: 'not_implemented_yet',
    227: 'not_implemented_yet',
    228: 'not_implemented_yet',
    229: 'not_implemented_yet',
    230: 'not_implemented_yet',
    231: 'not_implemented_yet',
    232: 'not_implemented_yet',
    233: 'not_implemented_yet',
    234: 'not_implemented_yet',
    235: 'not_implemented_yet',
    236: 'not_implemented_yet',
    237: 'not_implemented_yet',
    238: 'not_implemented_yet',
    239: 'not_implemented_yet',
    240: 'not_implemented_yet',
    241: 'not_implemented_yet',
    242: 'not_implemented_yet',
    243: 'not_implemented_yet',
    244: 'not_implemented_yet',
    245: 'not_implemented_yet',
    246: 'not_implemented_yet',
    247: 'not_implemented_yet',
    248: 'not_implemented_yet',
    249: 'not_implemented_yet',
    250: 'not_implemented_yet',
    251: 'not_implemented_yet',
    252: 'not_implemented_yet',
    253: 'not_implemented_yet',
    254: 'not_implemented_yet',
    255: 'not_implemented_yet'}

# For CASTLE TALK 2 ^ 8 - 1
TEXT_TO_MESSAGE = {
    'not_implemented_yet': 0,
    # 'not_implemented_yet':1 ,
    # 'not_implemented_yet':2 ,
    # 'not_implemented_yet':3 ,
    # 'not_implemented_yet':4 ,
    # 'not_implemented_yet':5 ,
    # 'not_implemented_yet':6 ,
    # 'not_implemented_yet':7 ,
    # 'not_implemented_yet':8 ,
    # 'not_implemented_yet':9 ,
    # 'not_implemented_yet':10 ,
    # 'not_implemented_yet':11 ,
    # 'not_implemented_yet':12 ,
    # 'not_implemented_yet':13 ,
    # 'not_implemented_yet':14 ,
    # 'not_implemented_yet':15 ,
    # 'not_implemented_yet':16 ,
    # 'not_implemented_yet':17 ,
    # 'not_implemented_yet':18 ,
    # 'not_implemented_yet':19 ,
    # 'not_implemented_yet':20 ,
    # 'not_implemented_yet':21 ,
    # 'not_implemented_yet':22 ,
    # 'not_implemented_yet':23 ,
    # 'not_implemented_yet':24 ,
    # 'not_implemented_yet':25 ,
    # 'not_implemented_yet':26 ,
    # 'not_implemented_yet':27 ,
    # 'not_implemented_yet':28 ,
    # 'not_implemented_yet':29 ,
    # 'not_implemented_yet':30 ,
    # 'not_implemented_yet':31 ,
    # 'not_implemented_yet':32 ,
    # 'not_implemented_yet':33 ,
    # 'not_implemented_yet':34 ,
    # 'not_implemented_yet':35 ,
    # 'not_implemented_yet':36 ,
    # 'not_implemented_yet':37 ,
    # 'not_implemented_yet':38 ,
    # 'not_implemented_yet':39 ,
    # 'not_implemented_yet':40 ,
    # 'not_implemented_yet':41 ,
    # 'not_implemented_yet':42 ,
    # 'not_implemented_yet':43 ,
    # 'not_implemented_yet':44 ,
    # 'not_implemented_yet':45 ,
    # 'not_implemented_yet':46 ,
    # 'not_implemented_yet':47 ,
    # 'not_implemented_yet':48 ,
    # 'not_implemented_yet':49 ,
    # 'not_implemented_yet':50 ,
    # 'not_implemented_yet':51 ,
    # 'not_implemented_yet':52 ,
    # 'not_implemented_yet':53 ,
    # 'not_implemented_yet':54 ,
    # 'not_implemented_yet':55 ,
    # 'not_implemented_yet':56 ,
    # 'not_implemented_yet':57 ,
    # 'not_implemented_yet':58 ,
    # 'not_implemented_yet':59 ,
    # 'not_implemented_yet':60 ,
    # 'not_implemented_yet':61 ,
    # 'not_implemented_yet':62 ,
    # 'not_implemented_yet':63 ,
    # 'not_implemented_yet':64 ,
    # 'not_implemented_yet':65 ,
    # 'not_implemented_yet':66 ,
    # 'not_implemented_yet':67 ,
    # 'not_implemented_yet':68 ,
    # 'not_implemented_yet':69 ,
    # 'not_implemented_yet':70 ,
    # 'not_implemented_yet':71 ,
    # 'not_implemented_yet':72 ,
    # 'not_implemented_yet':73 ,
    # 'not_implemented_yet':74 ,
    # 'not_implemented_yet':75 ,
    # 'not_implemented_yet':76 ,
    # 'not_implemented_yet':77 ,
    # 'not_implemented_yet':78 ,
    # 'not_implemented_yet':79 ,
    # 'not_implemented_yet':80 ,
    # 'not_implemented_yet':81 ,
    # 'not_implemented_yet':82 ,
    # 'not_implemented_yet':83 ,
    # 'not_implemented_yet':84 ,
    # 'not_implemented_yet':85 ,
    # 'not_implemented_yet':86 ,
    # 'not_implemented_yet':87 ,
    # 'not_implemented_yet':88 ,
    # 'not_implemented_yet':89 ,
    # 'not_implemented_yet':90 ,
    # 'not_implemented_yet':91 ,
    # 'not_implemented_yet':92 ,
    # 'not_implemented_yet':93 ,
    # 'not_implemented_yet':94 ,
    # 'not_implemented_yet':95 ,
    # 'not_implemented_yet':96 ,
    # 'not_implemented_yet':97 ,
    # 'not_implemented_yet':98 ,
    # 'not_implemented_yet':99 ,
    # 'not_implemented_yet':100 ,
    # 'not_implemented_yet':101 ,
    # 'not_implemented_yet':102 ,
    # 'not_implemented_yet':103 ,
    # 'not_implemented_yet':104 ,
    # 'not_implemented_yet':105 ,
    # 'not_implemented_yet':106 ,
    # 'not_implemented_yet':107 ,
    # 'not_implemented_yet':108 ,
    # 'not_implemented_yet':109 ,
    # 'not_implemented_yet':110 ,
    # 'not_implemented_yet':111 ,
    # 'not_implemented_yet':112 ,
    # 'not_implemented_yet':113 ,
    # 'not_implemented_yet':114 ,
    # 'not_implemented_yet':115 ,
    # 'not_implemented_yet':116 ,
    # 'not_implemented_yet':117 ,
    # 'not_implemented_yet':118 ,
    # 'not_implemented_yet':119 ,
    # 'not_implemented_yet':120 ,
    # 'not_implemented_yet':121 ,
    # 'not_implemented_yet':122 ,
    # 'not_implemented_yet':123 ,
    # 'not_implemented_yet':124 ,
    # 'not_implemented_yet':125 ,
    # 'not_implemented_yet':126 ,
    # 'not_implemented_yet':127 ,
    # 'not_implemented_yet':128 ,
    # 'not_implemented_yet':129 ,
    # 'not_implemented_yet':130 ,
    # 'not_implemented_yet':131 ,
    # 'not_implemented_yet':132 ,
    # 'not_implemented_yet':133 ,
    # 'not_implemented_yet':134 ,
    # 'not_implemented_yet':135 ,
    # 'not_implemented_yet':136 ,
    # 'not_implemented_yet':137 ,
    # 'not_implemented_yet':138 ,
    # 'not_implemented_yet':139 ,
    # 'not_implemented_yet':140 ,
    # 'not_implemented_yet':141 ,
    # 'not_implemented_yet':142 ,
    # 'not_implemented_yet':143 ,
    # 'not_implemented_yet':144 ,
    # 'not_implemented_yet':145 ,
    # 'not_implemented_yet':146 ,
    # 'not_implemented_yet':147 ,
    # 'not_implemented_yet':148 ,
    # 'not_implemented_yet':149 ,
    # 'not_implemented_yet':150 ,
    # 'not_implemented_yet':151 ,
    # 'not_implemented_yet':152 ,
    # 'not_implemented_yet':153 ,
    # 'not_implemented_yet':154 ,
    # 'not_implemented_yet':155 ,
    # 'not_implemented_yet':156 ,
    # 'not_implemented_yet':157 ,
    # 'not_implemented_yet':158 ,
    # 'not_implemented_yet':159 ,
    # 'not_implemented_yet':160 ,
    # 'not_implemented_yet':161 ,
    # 'not_implemented_yet':162 ,
    # 'not_implemented_yet':163 ,
    # 'not_implemented_yet':164 ,
    # 'not_implemented_yet':165 ,
    # 'not_implemented_yet':166 ,
    # 'not_implemented_yet':167 ,
    # 'not_implemented_yet':168 ,
    # 'not_implemented_yet':169 ,
    # 'not_implemented_yet':170 ,
    # 'not_implemented_yet':171 ,
    # 'not_implemented_yet':172 ,
    # 'not_implemented_yet':173 ,
    # 'not_implemented_yet':174 ,
    # 'not_implemented_yet':175 ,
    # 'not_implemented_yet':176 ,
    # 'not_implemented_yet':177 ,
    # 'not_implemented_yet':178 ,
    # 'not_implemented_yet':179 ,
    # 'not_implemented_yet':180 ,
    # 'not_implemented_yet':181 ,
    # 'not_implemented_yet':182 ,
    # 'not_implemented_yet':183 ,
    # 'not_implemented_yet':184 ,
    # 'not_implemented_yet':185 ,
    # 'not_implemented_yet':186 ,
    # 'not_implemented_yet':187 ,
    # 'not_implemented_yet':188 ,
    # 'not_implemented_yet':189 ,
    # 'not_implemented_yet':190 ,
    # 'not_implemented_yet':191 ,
    # 'not_implemented_yet':192 ,
    # 'not_implemented_yet':193 ,
    # 'not_implemented_yet':194 ,
    # 'not_implemented_yet':195 ,
    # 'not_implemented_yet':196 ,
    # 'not_implemented_yet':197 ,
    # 'not_implemented_yet':198 ,
    # 'not_implemented_yet':199 ,
    # 'not_implemented_yet':200 ,
    # 'not_implemented_yet':201 ,
    # 'not_implemented_yet':202 ,
    # 'not_implemented_yet':203 ,
    # 'not_implemented_yet':204 ,
    # 'not_implemented_yet':205 ,
    # 'not_implemented_yet':206 ,
    # 'not_implemented_yet':207 ,
    # 'not_implemented_yet':208 ,
    # 'not_implemented_yet':209 ,
    # 'not_implemented_yet':210 ,
    # 'not_implemented_yet':211 ,
    # 'not_implemented_yet':212 ,
    # 'not_implemented_yet':213 ,
    # 'not_implemented_yet':214 ,
    # 'not_implemented_yet':215 ,
    # 'not_implemented_yet':216 ,
    # 'not_implemented_yet':217 ,
    # 'not_implemented_yet':218 ,
    # 'not_implemented_yet':219 ,
    # 'not_implemented_yet':220 ,
    # 'not_implemented_yet':221 ,
    # 'not_implemented_yet':222 ,
    # 'not_implemented_yet':223 ,
    # 'not_implemented_yet':224 ,
    # 'not_implemented_yet':225 ,
    # 'not_implemented_yet':226 ,
    # 'not_implemented_yet':227 ,
    # 'not_implemented_yet':228 ,
    # 'not_implemented_yet':229 ,
    # 'not_implemented_yet':230 ,
    # 'not_implemented_yet':231 ,
    # 'not_implemented_yet':232 ,
    # 'not_implemented_yet':233 ,
    # 'not_implemented_yet':234 ,
    # 'not_implemented_yet':235 ,
    # 'not_implemented_yet':236 ,
    # 'not_implemented_yet':237 ,
    # 'not_implemented_yet':238 ,
    # 'not_implemented_yet':239 ,
    # 'not_implemented_yet':240 ,
    # 'not_implemented_yet':241 ,
    # 'not_implemented_yet':242 ,
    # 'not_implemented_yet':243 ,
    # 'not_implemented_yet':244 ,
    # 'not_implemented_yet':245 ,
    # 'not_implemented_yet':246 ,
    # 'not_implemented_yet':247 ,
    # 'not_implemented_yet':248 ,
    # 'not_implemented_yet':249 ,
    # 'not_implemented_yet':250 ,
    # 'not_implemented_yet':251 ,
    # 'not_implemented_yet':252 ,
    # 'not_implemented_yet':253 ,
    # 'not_implemented_yet':254 ,
    # 'not_implemented_yet':255
    'null': 256
}

#
